// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://nusfcwlkgoskebfsupnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51c2Zjd2xrZ29za2ViZnN1cG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzAxNzAsImV4cCI6MjA3MTM0NjE3MH0.QfNg4gaccjgxwCANtdb1IF85RSAdEgTNikPdAQMKPGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
